# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 12:08
from __future__ import unicode_literals

import demo.apps.catalogue.blocks
from django.db import migrations, models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0011_auto_20160616_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([(b'heading', wagtail.wagtailcore.blocks.CharBlock(classname=b'full title')), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), (b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'recommended_products', wagtail.wagtailcore.blocks.StructBlock([(b'title', wagtail.wagtailcore.blocks.CharBlock()), (b'subtitle', wagtail.wagtailcore.blocks.CharBlock()), (b'products', wagtail.wagtailcore.blocks.ListBlock(demo.apps.catalogue.blocks.ProductChooserBlock))]))], default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Name'),
        ),
    ]
